eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
        prefer-ip-address: true
server:
  port: 7903
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    sql-script-encoding: utf-8
  application:
    name: microservice-provider-user