user:
  userServicePath: http://localhost:7903/simple/
spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7910
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
